name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12
          check-latest: true
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12
          check-latest: true
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn test:ci
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.node }} == 12
